package com.gerenciamento.financas.model.enums;

public enum EnumTipoCategoria {
    DESPESAS_FIXAS,
    DESPESAS_DE_TRANSPORTE,
    DESPESAS_COM_ALIMENTACAO,
    DESPESAS_DE_SAUDE,
    DESPESAS_COM_EDUCACAO,
    DESPESAS_DE_LEAZER_E_ENTRETENIMENTO,
    DESPESAS_COM_VESTUARIO_E_BELEZA,
    DESPESAS_COM_FINANCAS_E_SERVICOS_BANCARIOS,
    RECEITAS,
    ECONOMIAS_E_INVESTIMENTOS
}
